### ISSUE TITLE
Incorrect (outdated) information in Visual C++ compiler error C2653 body

### ISSUE THREAD

**Issue by dodheim** [Microsoft/cpp-docs#2]
/docs/error-messages/compiler-errors-2/compiler-error-c2653.md presently reads:

> C2653 is also possible if you try to define a compound namespace; compound namespaces are not allowed in C++

Starting with Visual C++ 2015 Update 3 it is possible to define compound namespaces when compiling with `/std:c++latest`; C2653's description should explicitly mention this, as presently the statement is misleadingly overly-broad.

Proposal:

> C2653 is also possible if you try to define a compound namespace without using the `/std:c++latest` compiler option; compound namespaces were not allowed prior to C++17

**Comment by corob-msft** [comment]
We're sitting on a private fix; it will get synced up with the public bits along with other fixes, but I don't have a time frame yet.

**Comment by corob-msft** [comment]
Looks like the topic has been updated on the live site.
