### ISSUE TITLE
Docs on exit() function state that only the low-order byte of status will be made available to the caller, but this doesn't appear to be true?

### ISSUE THREAD

**Issue by ExplodingCabbage** [Microsoft/cpp-docs#27]
The offending paragraph, from https://msdn.microsoft.com/en-us/library/6wdz5232.aspx, is:

> Although the `exit`, `_Exit` and `_exit` calls do not return a value, the low-order byte of `status` is made available to the host environment or waiting calling process, if one exists, after the process exits.

Yet a quick experiment on my (Windows 10) machine suggests that status codes with more than 1 significant byte can still be communicated correctly to the caller. For instance, given this C program...

```
#include <stdio.h>

void main()
{
    printf("Hello, World!\n");
    exit(999999);
} 
```

... I can clearly get the full exit code:

```
C:\Users\markamery>cl test.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

test.c
Microsoft (R) Incremental Linker Version 14.10.25019.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj

C:\Users\markamery>test
Hello, World!

C:\Users\markamery>echo %errorlevel%
999999
```

**Comment by corob-msft** [comment]
This is almost certainly a holdover from the original POSIX documentation, which still specifies that exit()'s returned value to the system is the status & 0377. See http://man7.org/linux/man-pages/man3/exit.3.html for an example. It's not true of the current UCRT behavior, which can be seen in the UCRT library source code in the Windows SDK. On my system, that's found in "C:\Program Files (x86)\Windows Kits\10\Source\10.0.14393.0\ucrt\startup\exit.cpp". The various exit functions eventually make a Windows ExitProcess or TerminateProcess system call with the entire status value, a DWORD. I suspect the low-order byte business has never been true on Windows, in fact, but I don't have a legacy SDK from back in the day to verify that with right here to check.  

I'll look into updating the statement.

**Comment by corob-msft** [comment]
Forgot to resolve this back in May when the change was made.
